/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormKasus.java
 *
 * Created on Aug 1, 2022, 1:17:19 PM
 */
package kemahasiswaan_deri_10121069;

/**
 *
 * @author Deri
 */
public class FormKasus extends javax.swing.JFrame {

    /** Creates new form FormKasus */
    public FormKasus() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        ceker_banyak = new javax.swing.JTextField();
        usus_banyak = new javax.swing.JTextField();
        kepala_banyak = new javax.swing.JTextField();
        sayap_banyak = new javax.swing.JTextField();
        ayam_banyak = new javax.swing.JTextField();
        paket_banyak = new javax.swing.JTextField();
        mie_banyak = new javax.swing.JTextField();
        nasi_banyak = new javax.swing.JTextField();
        air_banyak = new javax.swing.JTextField();
        teh_banyak = new javax.swing.JTextField();
        ceker_jumlah = new javax.swing.JTextField();
        usus_jumlah = new javax.swing.JTextField();
        kepala_jumlah = new javax.swing.JTextField();
        sayap_jumlah = new javax.swing.JTextField();
        ayam_jumlah = new javax.swing.JTextField();
        mie_jumlah = new javax.swing.JTextField();
        paket_jumlah = new javax.swing.JTextField();
        nasi_jumlah = new javax.swing.JTextField();
        air_jumlah = new javax.swing.JTextField();
        teh_jumlah = new javax.swing.JTextField();
        pesan = new javax.swing.JToggleButton();
        jumlah = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        keluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(-8355712,true));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24));
        jLabel1.setForeground(new java.awt.Color(-1,true));
        jLabel1.setText("SIMULASI KASUS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(jLabel1)
                .addContainerGap(379, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18));
        jLabel2.setText("Daftar Makanan");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18));
        jLabel3.setText("Harga");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18));
        jLabel4.setText("Banyak");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18));
        jLabel5.setText("Jumlah");

        panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(-16777216,true), 3));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 18));
        jLabel6.setText("CEKER NDOWER");

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 18));
        jLabel7.setText("USUS NDOWER");

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 18));
        jLabel8.setText("SAYAP NDOWER");

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 18));
        jLabel9.setText("KEPALA NDOWER");

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 18));
        jLabel10.setText("AYAM GEPREK");

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 18));
        jLabel11.setText("MIE NELONGSO");

        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 18));
        jLabel12.setText("PAKET NASI AYAM GEPREK");

        jLabel13.setFont(new java.awt.Font("SansSerif", 0, 18));
        jLabel13.setText("NASI");

        jLabel14.setFont(new java.awt.Font("SansSerif", 0, 18));
        jLabel14.setText("AIR MINERAL");

        jLabel15.setFont(new java.awt.Font("SansSerif", 0, 18));
        jLabel15.setText("TEH PUCUK");

        jLabel16.setText("RP. 12.000");

        jLabel17.setText("RP. 12.000");

        jLabel18.setText("RP. 14.000");

        jLabel19.setText("RP. 10.000");

        jLabel20.setText("RP. 14.000");

        jLabel21.setText("RP. 12.000");

        jLabel22.setText("RP. 15.000");

        jLabel23.setText("RP. 7.000");

        jLabel24.setText("RP. 5.000");

        jLabel25.setText("RP. 7.000");

        ceker_banyak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceker_banyakActionPerformed(evt);
            }
        });
        ceker_banyak.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ceker_banyakKeyReleased(evt);
            }
        });

        usus_banyak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usus_banyakActionPerformed(evt);
            }
        });
        usus_banyak.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usus_banyakKeyReleased(evt);
            }
        });

        kepala_banyak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kepala_banyakActionPerformed(evt);
            }
        });
        kepala_banyak.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kepala_banyakKeyReleased(evt);
            }
        });

        sayap_banyak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sayap_banyakActionPerformed(evt);
            }
        });
        sayap_banyak.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sayap_banyakKeyReleased(evt);
            }
        });

        ayam_banyak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayam_banyakActionPerformed(evt);
            }
        });
        ayam_banyak.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ayam_banyakKeyReleased(evt);
            }
        });

        paket_banyak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paket_banyakActionPerformed(evt);
            }
        });
        paket_banyak.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                paket_banyakKeyReleased(evt);
            }
        });

        mie_banyak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mie_banyakActionPerformed(evt);
            }
        });
        mie_banyak.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mie_banyakKeyReleased(evt);
            }
        });

        nasi_banyak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nasi_banyakActionPerformed(evt);
            }
        });
        nasi_banyak.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nasi_banyakKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nasi_banyakKeyReleased(evt);
            }
        });

        air_banyak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                air_banyakActionPerformed(evt);
            }
        });
        air_banyak.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                air_banyakKeyReleased(evt);
            }
        });

        teh_banyak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teh_banyakActionPerformed(evt);
            }
        });
        teh_banyak.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                teh_banyakKeyReleased(evt);
            }
        });

        ceker_jumlah.setText("0");
        ceker_jumlah.setEnabled(false);

        usus_jumlah.setText("0");
        usus_jumlah.setEnabled(false);
        usus_jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usus_jumlahActionPerformed(evt);
            }
        });

        kepala_jumlah.setText("0");
        kepala_jumlah.setEnabled(false);

        sayap_jumlah.setText("0");
        sayap_jumlah.setEnabled(false);

        ayam_jumlah.setText("0");
        ayam_jumlah.setEnabled(false);

        mie_jumlah.setText("0");
        mie_jumlah.setEnabled(false);

        paket_jumlah.setText("0");
        paket_jumlah.setEnabled(false);

        nasi_jumlah.setText("0");
        nasi_jumlah.setEnabled(false);

        air_jumlah.setText("0");
        air_jumlah.setEnabled(false);

        teh_jumlah.setText("0");
        teh_jumlah.setEnabled(false);

        pesan.setText("Pesan");
        pesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesanActionPerformed(evt);
            }
        });

        jLabel26.setText("Jumlah Rp.");

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel11))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel12))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel13))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel14))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel15)))
                        .addGap(99, 99, 99)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ceker_banyak, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usus_banyak, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kepala_banyak, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sayap_banyak, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ayam_banyak, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paket_banyak, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mie_banyak, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nasi_banyak, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(air_banyak, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teh_banyak, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(94, 94, 94)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(teh_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ceker_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(usus_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sayap_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(kepala_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ayam_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mie_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nasi_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(air_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(paket_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(keluar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                        .addComponent(pesan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel17)
                    .addComponent(ceker_banyak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ceker_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usus_banyak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usus_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(sayap_banyak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sayap_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(kepala_banyak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kepala_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(ayam_banyak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ayam_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(19, 19, 19)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(mie_banyak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mie_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(19, 19, 19)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(paket_banyak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paket_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(16, 16, 16)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(nasi_banyak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nasi_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(air_banyak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(air_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(17, 17, 17)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(teh_banyak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teh_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addComponent(pesan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26)))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(keluar)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(195, 195, 195)
                .addComponent(jLabel4)
                .addGap(116, 116, 116)
                .addComponent(jLabel5)
                .addGap(69, 69, 69))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void ceker_banyakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceker_banyakActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_ceker_banyakActionPerformed

private void usus_banyakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usus_banyakActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_usus_banyakActionPerformed

private void kepala_banyakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kepala_banyakActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_kepala_banyakActionPerformed

private void sayap_banyakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sayap_banyakActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_sayap_banyakActionPerformed

private void ayam_banyakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayam_banyakActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_ayam_banyakActionPerformed

private void paket_banyakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paket_banyakActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_paket_banyakActionPerformed

private void mie_banyakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mie_banyakActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_mie_banyakActionPerformed

private void nasi_banyakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nasi_banyakActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_nasi_banyakActionPerformed

private void air_banyakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_air_banyakActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_air_banyakActionPerformed

private void teh_banyakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teh_banyakActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_teh_banyakActionPerformed

private void usus_jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usus_jumlahActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_usus_jumlahActionPerformed

private void ceker_banyakKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ceker_banyakKeyReleased
        int hasil;
        int a = Integer.parseInt(ceker_banyak.getText());
        hasil = a * 12000;
        ceker_jumlah.setText(Integer.toString(hasil));
}//GEN-LAST:event_ceker_banyakKeyReleased

private void usus_banyakKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usus_banyakKeyReleased
        int hasil;
        int a = Integer.parseInt(usus_banyak.getText());
        hasil = a * 12000;
        usus_jumlah.setText(Integer.toString(hasil));
}//GEN-LAST:event_usus_banyakKeyReleased

private void pesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesanActionPerformed
       int a,b,c,d,e,f,g,h,i,j;
       a = Integer.parseInt(ceker_jumlah.getText());
       b = Integer.parseInt(usus_jumlah.getText());
       c = Integer.parseInt(sayap_jumlah.getText());
       d = Integer.parseInt(kepala_jumlah.getText());
       e = Integer.parseInt(ayam_jumlah.getText());
       f = Integer.parseInt(mie_jumlah.getText());
       g = Integer.parseInt(paket_jumlah.getText());
       h = Integer.parseInt(nasi_jumlah.getText());
       i = Integer.parseInt(air_jumlah.getText());
       j = Integer.parseInt(teh_jumlah.getText());
       int hasil;
       hasil = a + b + c + d + e + f + g + h + i + j;
       jumlah.setText(Integer.toString(hasil));
}//GEN-LAST:event_pesanActionPerformed

private void sayap_banyakKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sayap_banyakKeyReleased
        int hasil;
        int a = Integer.parseInt(sayap_banyak.getText());
        hasil = a * 14000;
        sayap_jumlah.setText(Integer.toString(hasil));
}//GEN-LAST:event_sayap_banyakKeyReleased

private void kepala_banyakKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kepala_banyakKeyReleased
        int hasil;
        int a = Integer.parseInt(kepala_banyak.getText());
        hasil = a * 14000;
        kepala_jumlah.setText(Integer.toString(hasil));
}//GEN-LAST:event_kepala_banyakKeyReleased

private void ayam_banyakKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ayam_banyakKeyReleased
        int hasil;
        int a = Integer.parseInt(ayam_banyak.getText());
        hasil = a * 12000;
        ayam_jumlah.setText(Integer.toString(hasil));
}//GEN-LAST:event_ayam_banyakKeyReleased

private void mie_banyakKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mie_banyakKeyReleased
        int hasil;
        int a = Integer.parseInt(mie_banyak.getText());
        hasil = a * 10000;
        mie_jumlah.setText(Integer.toString(hasil));
}//GEN-LAST:event_mie_banyakKeyReleased

private void paket_banyakKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paket_banyakKeyReleased
        int hasil;
        int a = Integer.parseInt(paket_banyak.getText());
        hasil = a * 15000;
        paket_jumlah.setText(Integer.toString(hasil));
}//GEN-LAST:event_paket_banyakKeyReleased

private void nasi_banyakKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nasi_banyakKeyPressed
// TODO add your handling code here:
}//GEN-LAST:event_nasi_banyakKeyPressed

private void nasi_banyakKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nasi_banyakKeyReleased
        int hasil;
        int a = Integer.parseInt(nasi_banyak.getText());
        hasil = a * 5000;
        nasi_jumlah.setText(Integer.toString(hasil));
}//GEN-LAST:event_nasi_banyakKeyReleased

private void air_banyakKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_air_banyakKeyReleased
        int hasil;
        int a = Integer.parseInt(air_banyak.getText());
        hasil = a * 7000;
        air_jumlah.setText(Integer.toString(hasil));
}//GEN-LAST:event_air_banyakKeyReleased

private void teh_banyakKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teh_banyakKeyReleased
        int hasil;
        int a = Integer.parseInt(teh_banyak.getText());
        hasil = a * 7000;
        teh_jumlah.setText(Integer.toString(hasil));
}//GEN-LAST:event_teh_banyakKeyReleased

private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
// TODO add your handling code here:
    FormUtama utama = new FormUtama();
    utama.setVisible(true);
    this.setVisible(false);
    
}//GEN-LAST:event_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormKasus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormKasus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormKasus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormKasus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FormKasus().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField air_banyak;
    private javax.swing.JTextField air_jumlah;
    private javax.swing.JTextField ayam_banyak;
    private javax.swing.JTextField ayam_jumlah;
    private javax.swing.JTextField ceker_banyak;
    private javax.swing.JTextField ceker_jumlah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField kepala_banyak;
    private javax.swing.JTextField kepala_jumlah;
    private javax.swing.JTextField mie_banyak;
    private javax.swing.JTextField mie_jumlah;
    private javax.swing.JTextField nasi_banyak;
    private javax.swing.JTextField nasi_jumlah;
    private javax.swing.JTextField paket_banyak;
    private javax.swing.JTextField paket_jumlah;
    private javax.swing.JPanel panel;
    private javax.swing.JToggleButton pesan;
    private javax.swing.JTextField sayap_banyak;
    private javax.swing.JTextField sayap_jumlah;
    private javax.swing.JTextField teh_banyak;
    private javax.swing.JTextField teh_jumlah;
    private javax.swing.JTextField usus_banyak;
    private javax.swing.JTextField usus_jumlah;
    // End of variables declaration//GEN-END:variables
}
