/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormMataKuliah.java
 *
 * Created on Jul 26, 2022, 6:12:48 PM
 */
package kemahasiswaan_deri_10121069;
import javax.swing.*;
//Fungsi Import Digunakan Untuk Sql
import java.sql.*;
/**
 *
 * @author Deri
 */
public class FormMataKuliah extends javax.swing.JFrame {
    //Deklarasi Variabel
    koneksi dbsetting;
    String driver,database,user,pass;
    Object tabel;

    /** Creates new form FormMataKuliah */
    public FormMataKuliah() 
    {
        initComponents();
        dbsetting = new koneksi();
        driver = dbsetting.SettingPanel("DBDriver");
        database = dbsetting.SettingPanel("DBDatabase");
        user = dbsetting.SettingPanel("DBUsername");
        pass = dbsetting.SettingPanel("DBPassword");
        
        tabel_mk.setModel(tableModel);
        settableload();
    }
    private javax.swing.table.DefaultTableModel tableModel = getDefaultTabelModel();
    private javax.swing.table.DefaultTableModel getDefaultTabelModel()
    {
     //Membuat Judul Header
     return new javax.swing.table.DefaultTableModel
     (
        new Object [][] {},
        new String [] {"NOMOR MK",
                       "NAMA MK",
                       }
     )
     //Disabel Perubahan Pada Grid
     {
         boolean[] canEdit = new boolean[]
         {
            false, false,
         };
         
         public boolean isCellEditable(int rowIndex, int columnIndex)
         {
           return canEdit[columnIndex];
         }
      };
                  
    }
    String data[] = new String[2];
    private void settableload()
    {
        String stat = "";
        try
        {
            Class.forName(driver);
            Connection kon = DriverManager.getConnection(database,user,pass);
            Statement stt = kon.createStatement();
            String SQL = "select * from mata_kuliah";
            ResultSet res = stt.executeQuery(SQL);
            while(res.next())
            {
                data[0] = res.getString(1);
                data[1] = res.getString(2);
                tableModel.addRow(data);
            }
            res.close();
            stt.close();
            kon.close();
           
        }
        catch(Exception ex)
        {
            System.err.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, ex.getMessage(),"Error",
                    JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
        
    }
    public void membersihkan_teks()
    {
        nomor_mk.setText("");
        nama_mk.setText("");
    }
    public void nonaktif_text()
    {
        nomor_mk.setEnabled(false);
        nama_mk.setEnabled(false);

    }        
    public void aktif_teks()
    {
        nomor_mk.setEnabled(true);
        nama_mk.setEnabled(true);
    }
    int row = 0;
    public void tampil_field()
    {
        row = tabel_mk.getSelectedRow();
        nomor_mk.setText(tableModel.getValueAt(row, 0).toString());
        nama_mk.setText(tableModel.getValueAt(row, 1).toString());
        simpan.setEnabled(false);
        ubah.setEnabled(true);
        hapus.setEnabled(true);
        batal.setEnabled(false);
        aktif_teks();
                
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cari_data = new javax.swing.JTextField();
        cari = new javax.swing.JButton();
        tampil = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        nomor_mk = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nama_mk = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_mk = new javax.swing.JTable();
        tambah = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        keluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(-8355712,true));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24));
        jLabel1.setForeground(new java.awt.Color(-1,true));
        jLabel1.setText("FORM MATA KULIAH");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(jLabel1)
                .addContainerGap(368, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(-16777216,true), 2), "PENCARIAN MATA KULIAH"));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18));
        jLabel2.setText("MASUKKAN DATA (NOMOR MK)");

        cari_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari_dataActionPerformed(evt);
            }
        });

        cari.setText("CARI");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });

        tampil.setText("TAMPILKAN SEMUA");
        tampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(38, 38, 38)
                .addComponent(cari_data, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(cari)
                .addGap(46, 46, 46)
                .addComponent(tampil)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cari_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cari)
                    .addComponent(tampil))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jLabel3.setText("NOMOR M.K");

        jLabel4.setText("NAMA M.K");

        tabel_mk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nomor MK", "Nama MK"
            }
        ));
        tabel_mk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_mkMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_mk);

        tambah.setText("TAMBAH");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        ubah.setText("UBAH");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });

        hapus.setText("HAPUS");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        simpan.setText("SIMPAN");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        batal.setText("BATAL");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });

        keluar.setText("KELUAR");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(nomor_mk, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126)
                .addComponent(jLabel4)
                .addGap(32, 32, 32)
                .addComponent(nama_mk, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 923, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(batal, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addComponent(keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nomor_mk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(nama_mk, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambah)
                    .addComponent(ubah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapus)
                    .addComponent(simpan)
                    .addComponent(batal)
                    .addComponent(keluar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void cari_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari_dataActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_cari_dataActionPerformed

private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
// TODO add your handling code here:
    String nomorMK = nomor_mk.getText();
    String namaMK = nama_mk.getText();
    
   if ((nomorMK.isEmpty()) | (namaMK.isEmpty()))
   {
       JOptionPane.showMessageDialog(null,"Data tidak boleh kosong, Silahkan dilengkapi");
       nomor_mk.requestFocus();
   }
   else
   {
       try
       {
           Class.forName(driver);
           Connection kon = DriverManager.getConnection(database,user,pass);
           Statement stt = kon.createStatement();
           String SQL = "UPDATE mata_kuliah "+ 
                   "SET kode_mk = '"+nomorMK+"',nama_mk = '"+namaMK+
                   "'WHERE "
                   + " kode_mk ='"+tableModel.getValueAt(row, 0).toString()+"';";
           stt.executeUpdate(SQL);
           data [0] = nomorMK;
           data [1] = namaMK;
           tableModel.removeRow(row);
           tableModel.insertRow(row, data);
           stt.close();
           kon.close();
           JOptionPane.showMessageDialog(this, "Data Berhasil Diubah");
           membersihkan_teks();
           simpan.setEnabled(false);
           nonaktif_text();
       }
       catch (Exception ex)
       {
         System.err.println(ex.getMessage());
       }
   }
}//GEN-LAST:event_ubahActionPerformed

private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
// TODO add your handling code here:
    membersihkan_teks();
    nomor_mk.requestFocus();
    tambah.setEnabled(false);
    simpan.setEnabled(true);
    ubah.setEnabled(false);
    hapus.setEnabled(false);
    keluar.setEnabled(false);
    aktif_teks();

    
}//GEN-LAST:event_tambahActionPerformed

private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
// TODO add your handling code here:
    String data [] = new String[3];
    
    if ((nama_mk.getText().isEmpty()) || (nomor_mk.getText().isEmpty()))
    {
        JOptionPane.showMessageDialog(null,
                "Data tidak boleh kosong, silahkan dilengkapi");
        nomor_mk.requestFocus();
    }
    else
    {
        try
        {
            Class.forName(driver);
            Connection kon = DriverManager.getConnection(
                               database,
                               user,
                               pass);
            Statement stt = kon.createStatement();
            String    SQL = "INSERT INTO mata_kuliah(kode_mk,nama_mk) "
                    + "VALUES('"+nomor_mk.getText()+"','"+nama_mk.getText()+"')";
            stt.executeUpdate(SQL);
            data[0] = nomor_mk.getText();
            data[1] = nama_mk.getText();
            tableModel.insertRow(0, data);
            stt.close();
            kon.close();
            JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan");
            membersihkan_teks();
            simpan.setEnabled(false);
            nonaktif_text();
            simpan.setEnabled(false);
            nonaktif_text();
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null,
                    ex.getMessage(),"Error",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }
}//GEN-LAST:event_simpanActionPerformed

private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
// TODO add your handling code here:
    try
    {
           Class.forName(driver);
           Connection kon = DriverManager.getConnection(database,user,pass);
           Statement stt = kon.createStatement();
           String SQL = "Delete from mata_kuliah "                     
                   + "WHERE "
                   + " kode_mk ='"+tableModel.getValueAt(row, 0).toString()+"'";
           stt.executeUpdate(SQL);
           tableModel.removeRow(row);
           stt.close();
           kon.close();
           JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
           membersihkan_teks();
    }
    catch (Exception ex)
       {
         System.err.println(ex.getMessage());
       }
}//GEN-LAST:event_hapusActionPerformed

private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
// TODO add your handling code here:
    String cari = cari_data.getText();
    if (cari.isEmpty())
    {
        JOptionPane.showMessageDialog(this,"Data Tidak Boleh Kosong");
    }
    else
    //Gunakan Querry untuk mencari
    tableModel.setRowCount(0);
    try
    {
     Class.forName(driver);
     Connection kon = DriverManager.getConnection(database,user,pass);
     Statement stt = kon.createStatement();
     String SQL = "select * from mata_kuliah where kode_mk='"+
                   cari+"'";
     ResultSet res = stt.executeQuery(SQL);
     while(res.next())
     {
                data[0] = res.getString(1);
                data[1] = res.getString(2);
               tableModel.addRow(data);
      }
            res.close();
            stt.close();
            kon.close();
        }
        catch(Exception ex)
        {
            System.err.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, ex.getMessage(),"Error",
                    JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
}//GEN-LAST:event_cariActionPerformed

private void tabel_mkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_mkMouseClicked
// TODO add your handling code here:
    if(evt.getClickCount() == 1)
    {
        tampil_field();
    }
    
}//GEN-LAST:event_tabel_mkMouseClicked

private void tampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilActionPerformed
// TODO add your handling code here:
    tableModel.setRowCount(0);
    settableload();
}//GEN-LAST:event_tampilActionPerformed

private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
// TODO add your handling code here:
    FormUtama utama = new FormUtama();
    utama.setVisible(true);
    this.setVisible(false);
}//GEN-LAST:event_keluarActionPerformed

private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
// TODO add your handling code here:
    membersihkan_teks();
    keluar.setEnabled(true);
}//GEN-LAST:event_batalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMataKuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMataKuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMataKuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMataKuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FormMataKuliah().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal;
    private javax.swing.JButton cari;
    private javax.swing.JTextField cari_data;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField nama_mk;
    private javax.swing.JTextField nomor_mk;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabel_mk;
    private javax.swing.JButton tambah;
    private javax.swing.JButton tampil;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables
}
